FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements.apicenter.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# <--- Важно: копируем всю директорию app
COPY ./app /app/app 

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
