from pydantic import BaseModel, Field
from typing import Optional, List # Added List
from datetime import datetime

# Attempt to import settings. If this fails, I'll need to rethink default value application.
from app.core.config import settings

class LLMConfigSchema(BaseModel):
    provider: str = Field(default="openrouter", description="LLM provider (e.g., 'openrouter', 'openai')")
    model_name: str = Field(default=settings.DEFAULT_LLM_MODEL, description="Name of the LLM model")
    # API key is sensitive, should not be part of response schemas directly.
    # It will be handled in the Beanie Document model (e.g., write-only or specific projection)
    # For input during create/update, it can be accepted.
    api_key: Optional[str] = Field(None, description="API key for the LLM provider. Store securely.")
    temperature: float = Field(default=settings.LLM_TEMPERATURE, ge=0.0, le=2.0, description="LLM temperature")
    max_tokens: int = Field(default=settings.LLM_MAX_TOKENS, gt=0, description="LLM max tokens")
    custom_prompt_prefix: Optional[str] = Field(None, description="Custom prefix for the system prompt for this client")

    class Config:
        extra = "ignore"
        from_attributes = True


class ClientConfigurationBaseSchema(BaseModel):
    client_name: str = Field(..., min_length=1, description="Human-readable name of the client")
    persona: str = Field(default=settings.MVP_CLIENT_PERSONA, description="AI assistant's persona for this client")
    tone: str = Field(default=settings.MVP_CLIENT_TONE, description="AI assistant's tone for this client")
    business_type: str = Field(default=settings.MVP_BUSINESS_TYPE, description="Type of business/domain for this client")
    default_lang: str = Field(default=settings.DEFAULT_LANG_API, description="Default language for this client (ISO 639-1 code)")
    llm_config: LLMConfigSchema = Field(default_factory=LLMConfigSchema, description="LLM configuration for this client")
    history_max_messages: int = Field(default=settings.HISTORY_MAX_MESSAGES, gt=0, description="Max conversation history messages for LLM")
    is_active: bool = Field(default=True, description="Whether this client configuration is active")
    # client_secret_plain: Will be accepted in Create/Update schemas, but not part of base or response. Hashing handled in service.

    class Config:
        extra = "ignore"
        from_attributes = True


class ClientConfigurationCreateSchema(ClientConfigurationBaseSchema):
    # client_id is not usually set by user on creation, but generated by system or can be an optional slug.
    # Let's make it optional. If provided, it should be validated (e.g. slug format).
    # If not provided, Beanie model's default_factory for client_id (e.g. uuid4) will be used.
    client_id: Optional[str] = Field(None, description="Optional custom client ID (slug format recommended if provided). If None, will be auto-generated by the system.", pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    client_secret_plain: Optional[str] = Field(None, min_length=8, description="Plain text client secret. Will be hashed before saving if provided.")


class ClientConfigurationUpdateSchema(BaseModel): # Not inheriting from Base to allow all fields to be optional
    client_name: Optional[str] = Field(None, min_length=1)
    persona: Optional[str] = None
    tone: Optional[str] = None
    business_type: Optional[str] = None
    default_lang: Optional[str] = None
    llm_config: Optional[LLMConfigSchema] = None # Allows partial update of llm_config as well
    history_max_messages: Optional[int] = Field(None, gt=0)
    is_active: Optional[bool] = None
    client_secret_plain: Optional[str] = Field(None, min_length=8, description="New plain text client secret to update. Will be hashed.")

    class Config:
        extra = "ignore"
        from_attributes = True


class ClientConfigurationResponseSchema(ClientConfigurationBaseSchema):
    client_id: str = Field(..., description="Unique identifier for the client")

    # Exclude sensitive fields from the response by default
    # llm_config will be transformed to hide api_key
    llm_config: LLMConfigSchema # Overriding to ensure it's present in response, transformation will handle api_key

    # Add fields to indicate sensitive data presence without exposing it
    has_client_secret: bool = Field(description="Indicates if a client secret is set")
    llm_api_key_is_set: bool = Field(description="Indicates if an API key is configured for the LLM")

    created_at: datetime
    updated_at: datetime

    class Config:
        extra = "ignore"
        from_attributes = True
        # Note: Actual exclusion/transformation of sensitive fields like api_key in llm_config
        # or client_secret_hashed from the Beanie model will be handled by projection
        # in the service layer or by defining a specific response model for the Beanie document.


class PaginatedClientResponseSchema(BaseModel):
    total: int
    page: int
    size: int
    results: List[ClientConfigurationResponseSchema]
